dataSource.className=org.postgresql.ds.PGSimpleDataSource
dataSource.user=postgres
dataSource.password=root
dataSource.databaseName=kfc_db
dataSource.portNumber=5432
dataSource.serverName=localhost

security.token.prefix=Bearer\ 
security.token.secret=SecretKeyToGenerateJWT
security.token.expiration=3600000
security.refresh.token.expiration=86400000
security.admin.login=admin@kfc.com
security.admin.password.hash=4d50663386a0afd1cffba5a037dc6a6a9c3d3f86ea509473a08bd0cff388ff94