version: "3.8"
name: kfc-services
services:
  postgres:
    image: postgres:17.2
    ports:
      - "5432:5432"
    volumes:
      - kfc_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: kfc_db

  wildfly:
    image: ghcr.io/otipz19/ukma_db_project_kfc_backend:main
    ports:
      - "8080:8080"
      - "9990:9990"
    environment:
      DB_HOST: "" # todo: fix this

volumes:
  kfc_volume: