name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'corretto'
        cache: maven
    - name: Package
      run: mvn -B package
    - uses: actions/upload-artifact@v4
      with:
        name: KFC
        path: ./target/KFC.war
      
    
    
